/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteLibraryRouteImport } from './routes/_site.library'
import { Route as SiteOpportunitiesRouteImport } from './routes/_site.opportunities'
import { Route as SiteProblemsRouteImport } from './routes/_site.problems'
import { Route as SiteProfileRouteImport } from './routes/_site.profile'
import { Route as SiteResourcesRouteImport } from './routes/_site.resources'
import { Route as SiteSearchRouteImport } from './routes/_site.search'
import { Route as SiteStudioRouteImport } from './routes/_site.studio'
import { Route as SiteUpdatesRouteImport } from './routes/_site.updates'
import { Route as SiteArticlesIndexRouteImport } from './routes/_site.articles.index'
import { Route as SiteArticlesSlugRouteImport } from './routes/_site.articles.$slug'
import { Route as SiteCareersIndexRouteImport } from './routes/_site.careers.index'
import { Route as SiteCareersSlugRouteImport } from './routes/_site.careers.$slug'
import { Route as SiteRoadmapsIndexRouteImport } from './routes/_site.roadmaps.index'
import { Route as SiteRoadmapsSlugRouteImport } from './routes/_site.roadmaps.$slug'
import { Route as SiteSectionSlugRouteImport } from './routes/_site.section.$slug'
import { Route as SiteStudioIndexRouteImport } from './routes/_site.studio.index'
import { Route as SiteStudioCollectionIndexRouteImport } from './routes/_site.studio.$collection.index'
import { Route as SiteStudioCollectionIdRouteImport } from './routes/_site.studio.$collection.$id'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLibraryRoute = SiteLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOpportunitiesRoute = SiteOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProblemsRoute = SiteProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProfileRoute = SiteProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SiteRoute,
} as any)
const SiteResourcesRoute = SiteResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSearchRoute = SiteSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStudioRoute = SiteStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => SiteRoute,
} as any)
const SiteUpdatesRoute = SiteUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => SiteRoute,
} as any)
const SiteArticlesIndexRoute = SiteArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteArticlesSlugRoute = SiteArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCareersIndexRoute = SiteCareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCareersSlugRoute = SiteCareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRoadmapsIndexRoute = SiteRoadmapsIndexRouteImport.update({
  id: '/roadmaps/',
  path: '/roadmaps/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRoadmapsSlugRoute = SiteRoadmapsSlugRouteImport.update({
  id: '/roadmaps/$slug',
  path: '/roadmaps/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSectionSlugRoute = SiteSectionSlugRouteImport.update({
  id: '/section/$slug',
  path: '/section/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStudioIndexRoute = SiteStudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteStudioRoute,
} as any)
const SiteStudioCollectionIndexRoute =
  SiteStudioCollectionIndexRouteImport.update({
    id: '/$collection/',
    path: '/$collection/',
    getParentRoute: () => SiteStudioRoute,
  } as any)
const SiteStudioCollectionIdRoute = SiteStudioCollectionIdRouteImport.update({
  id: '/$collection/$id',
  path: '/$collection/$id',
  getParentRoute: () => SiteStudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRoute
  '/library': typeof SiteLibraryRoute
  '/opportunities': typeof SiteOpportunitiesRoute
  '/problems': typeof SiteProblemsRoute
  '/profile': typeof SiteProfileRoute
  '/resources': typeof SiteResourcesRoute
  '/search': typeof SiteSearchRoute
  '/studio': typeof SiteStudioRouteWithChildren
  '/updates': typeof SiteUpdatesRoute
  '/articles/$slug': typeof SiteArticlesSlugRoute
  '/careers/$slug': typeof SiteCareersSlugRoute
  '/roadmaps/$slug': typeof SiteRoadmapsSlugRoute
  '/section/$slug': typeof SiteSectionSlugRoute
  '/articles/': typeof SiteArticlesIndexRoute
  '/careers/': typeof SiteCareersIndexRoute
  '/roadmaps/': typeof SiteRoadmapsIndexRoute
  '/studio/': typeof SiteStudioIndexRoute
  '/studio/$collection/$id': typeof SiteStudioCollectionIdRoute
  '/studio/$collection/': typeof SiteStudioCollectionIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/library': typeof SiteLibraryRoute
  '/opportunities': typeof SiteOpportunitiesRoute
  '/problems': typeof SiteProblemsRoute
  '/profile': typeof SiteProfileRoute
  '/resources': typeof SiteResourcesRoute
  '/search': typeof SiteSearchRoute
  '/updates': typeof SiteUpdatesRoute
  '/': typeof SiteIndexRoute
  '/articles/$slug': typeof SiteArticlesSlugRoute
  '/careers/$slug': typeof SiteCareersSlugRoute
  '/roadmaps/$slug': typeof SiteRoadmapsSlugRoute
  '/section/$slug': typeof SiteSectionSlugRoute
  '/articles': typeof SiteArticlesIndexRoute
  '/careers': typeof SiteCareersIndexRoute
  '/roadmaps': typeof SiteRoadmapsIndexRoute
  '/studio': typeof SiteStudioIndexRoute
  '/studio/$collection/$id': typeof SiteStudioCollectionIdRoute
  '/studio/$collection': typeof SiteStudioCollectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_site/library': typeof SiteLibraryRoute
  '/_site/opportunities': typeof SiteOpportunitiesRoute
  '/_site/problems': typeof SiteProblemsRoute
  '/_site/profile': typeof SiteProfileRoute
  '/_site/resources': typeof SiteResourcesRoute
  '/_site/search': typeof SiteSearchRoute
  '/_site/studio': typeof SiteStudioRouteWithChildren
  '/_site/updates': typeof SiteUpdatesRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/articles/$slug': typeof SiteArticlesSlugRoute
  '/_site/careers/$slug': typeof SiteCareersSlugRoute
  '/_site/roadmaps/$slug': typeof SiteRoadmapsSlugRoute
  '/_site/section/$slug': typeof SiteSectionSlugRoute
  '/_site/articles/': typeof SiteArticlesIndexRoute
  '/_site/careers/': typeof SiteCareersIndexRoute
  '/_site/roadmaps/': typeof SiteRoadmapsIndexRoute
  '/_site/studio/': typeof SiteStudioIndexRoute
  '/_site/studio/$collection/$id': typeof SiteStudioCollectionIdRoute
  '/_site/studio/$collection/': typeof SiteStudioCollectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/library'
    | '/opportunities'
    | '/problems'
    | '/profile'
    | '/resources'
    | '/search'
    | '/studio'
    | '/updates'
    | '/articles/$slug'
    | '/careers/$slug'
    | '/roadmaps/$slug'
    | '/section/$slug'
    | '/articles/'
    | '/careers/'
    | '/roadmaps/'
    | '/studio/'
    | '/studio/$collection/$id'
    | '/studio/$collection/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/library'
    | '/opportunities'
    | '/problems'
    | '/profile'
    | '/resources'
    | '/search'
    | '/updates'
    | '/'
    | '/articles/$slug'
    | '/careers/$slug'
    | '/roadmaps/$slug'
    | '/section/$slug'
    | '/articles'
    | '/careers'
    | '/roadmaps'
    | '/studio'
    | '/studio/$collection/$id'
    | '/studio/$collection'
  id:
    | '__root__'
    | '/_site'
    | '/auth'
    | '/_site/library'
    | '/_site/opportunities'
    | '/_site/problems'
    | '/_site/profile'
    | '/_site/resources'
    | '/_site/search'
    | '/_site/studio'
    | '/_site/updates'
    | '/_site/'
    | '/_site/articles/$slug'
    | '/_site/careers/$slug'
    | '/_site/roadmaps/$slug'
    | '/_site/section/$slug'
    | '/_site/articles/'
    | '/_site/careers/'
    | '/_site/roadmaps/'
    | '/_site/studio/'
    | '/_site/studio/$collection/$id'
    | '/_site/studio/$collection/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/library': {
      id: '/_site/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof SiteLibraryRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/opportunities': {
      id: '/_site/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof SiteOpportunitiesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/problems': {
      id: '/_site/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof SiteProblemsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/profile': {
      id: '/_site/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SiteProfileRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/resources': {
      id: '/_site/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof SiteResourcesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/search': {
      id: '/_site/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SiteSearchRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/studio': {
      id: '/_site/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof SiteStudioRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/updates': {
      id: '/_site/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof SiteUpdatesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/articles/': {
      id: '/_site/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof SiteArticlesIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/articles/$slug': {
      id: '/_site/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof SiteArticlesSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/careers/': {
      id: '/_site/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof SiteCareersIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/careers/$slug': {
      id: '/_site/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof SiteCareersSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/roadmaps/': {
      id: '/_site/roadmaps/'
      path: '/roadmaps'
      fullPath: '/roadmaps/'
      preLoaderRoute: typeof SiteRoadmapsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/roadmaps/$slug': {
      id: '/_site/roadmaps/$slug'
      path: '/roadmaps/$slug'
      fullPath: '/roadmaps/$slug'
      preLoaderRoute: typeof SiteRoadmapsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/section/$slug': {
      id: '/_site/section/$slug'
      path: '/section/$slug'
      fullPath: '/section/$slug'
      preLoaderRoute: typeof SiteSectionSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/studio/': {
      id: '/_site/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof SiteStudioIndexRouteImport
      parentRoute: typeof SiteStudioRoute
    }
    '/_site/studio/$collection/': {
      id: '/_site/studio/$collection/'
      path: '/$collection'
      fullPath: '/studio/$collection/'
      preLoaderRoute: typeof SiteStudioCollectionIndexRouteImport
      parentRoute: typeof SiteStudioRoute
    }
    '/_site/studio/$collection/$id': {
      id: '/_site/studio/$collection/$id'
      path: '/$collection/$id'
      fullPath: '/studio/$collection/$id'
      preLoaderRoute: typeof SiteStudioCollectionIdRouteImport
      parentRoute: typeof SiteStudioRoute
    }
  }
}

interface SiteStudioRouteChildren {
  SiteStudioIndexRoute: typeof SiteStudioIndexRoute
  SiteStudioCollectionIdRoute: typeof SiteStudioCollectionIdRoute
  SiteStudioCollectionIndexRoute: typeof SiteStudioCollectionIndexRoute
}

const SiteStudioRouteChildren: SiteStudioRouteChildren = {
  SiteStudioIndexRoute: SiteStudioIndexRoute,
  SiteStudioCollectionIdRoute: SiteStudioCollectionIdRoute,
  SiteStudioCollectionIndexRoute: SiteStudioCollectionIndexRoute,
}

const SiteStudioRouteWithChildren = SiteStudioRoute._addFileChildren(
  SiteStudioRouteChildren,
)

interface SiteRouteChildren {
  SiteLibraryRoute: typeof SiteLibraryRoute
  SiteOpportunitiesRoute: typeof SiteOpportunitiesRoute
  SiteProblemsRoute: typeof SiteProblemsRoute
  SiteProfileRoute: typeof SiteProfileRoute
  SiteResourcesRoute: typeof SiteResourcesRoute
  SiteSearchRoute: typeof SiteSearchRoute
  SiteStudioRoute: typeof SiteStudioRouteWithChildren
  SiteUpdatesRoute: typeof SiteUpdatesRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteArticlesSlugRoute: typeof SiteArticlesSlugRoute
  SiteCareersSlugRoute: typeof SiteCareersSlugRoute
  SiteRoadmapsSlugRoute: typeof SiteRoadmapsSlugRoute
  SiteSectionSlugRoute: typeof SiteSectionSlugRoute
  SiteArticlesIndexRoute: typeof SiteArticlesIndexRoute
  SiteCareersIndexRoute: typeof SiteCareersIndexRoute
  SiteRoadmapsIndexRoute: typeof SiteRoadmapsIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteLibraryRoute: SiteLibraryRoute,
  SiteOpportunitiesRoute: SiteOpportunitiesRoute,
  SiteProblemsRoute: SiteProblemsRoute,
  SiteProfileRoute: SiteProfileRoute,
  SiteResourcesRoute: SiteResourcesRoute,
  SiteSearchRoute: SiteSearchRoute,
  SiteStudioRoute: SiteStudioRouteWithChildren,
  SiteUpdatesRoute: SiteUpdatesRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteArticlesSlugRoute: SiteArticlesSlugRoute,
  SiteCareersSlugRoute: SiteCareersSlugRoute,
  SiteRoadmapsSlugRoute: SiteRoadmapsSlugRoute,
  SiteSectionSlugRoute: SiteSectionSlugRoute,
  SiteArticlesIndexRoute: SiteArticlesIndexRoute,
  SiteCareersIndexRoute: SiteCareersIndexRoute,
  SiteRoadmapsIndexRoute: SiteRoadmapsIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
