/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteArticlesIndexRouteImport } from './routes/_site.articles.index'
import { Route as SiteArticlesSlugRouteImport } from './routes/_site.articles.$slug'
import { Route as SiteLearnIndexRouteImport } from './routes/_site.learn.index'
import { Route as SiteRoadmapsIndexRouteImport } from './routes/_site.roadmaps.index'
import { Route as SiteRoadmapsSlugRouteImport } from './routes/_site.roadmaps.$slug'
import { Route as SiteLearnPathSlugIndexRouteImport } from './routes/_site.learn.$pathSlug.index'
import { Route as SiteLearnPathSlugLessonSlugRouteImport } from './routes/_site.learn.$pathSlug.$lessonSlug'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteArticlesIndexRoute = SiteArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteArticlesSlugRoute = SiteArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLearnIndexRoute = SiteLearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRoadmapsIndexRoute = SiteRoadmapsIndexRouteImport.update({
  id: '/roadmaps/',
  path: '/roadmaps/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRoadmapsSlugRoute = SiteRoadmapsSlugRouteImport.update({
  id: '/roadmaps/$slug',
  path: '/roadmaps/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLearnPathSlugIndexRoute = SiteLearnPathSlugIndexRouteImport.update({
  id: '/learn/$pathSlug/',
  path: '/learn/$pathSlug/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLearnPathSlugLessonSlugRoute =
  SiteLearnPathSlugLessonSlugRouteImport.update({
    id: '/learn/$pathSlug/$lessonSlug',
    path: '/learn/$pathSlug/$lessonSlug',
    getParentRoute: () => SiteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/articles/$slug': typeof SiteArticlesSlugRoute
  '/roadmaps/$slug': typeof SiteRoadmapsSlugRoute
  '/articles/': typeof SiteArticlesIndexRoute
  '/learn/': typeof SiteLearnIndexRoute
  '/roadmaps/': typeof SiteRoadmapsIndexRoute
  '/learn/$pathSlug/$lessonSlug': typeof SiteLearnPathSlugLessonSlugRoute
  '/learn/$pathSlug/': typeof SiteLearnPathSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/articles/$slug': typeof SiteArticlesSlugRoute
  '/roadmaps/$slug': typeof SiteRoadmapsSlugRoute
  '/articles': typeof SiteArticlesIndexRoute
  '/learn': typeof SiteLearnIndexRoute
  '/roadmaps': typeof SiteRoadmapsIndexRoute
  '/learn/$pathSlug/$lessonSlug': typeof SiteLearnPathSlugLessonSlugRoute
  '/learn/$pathSlug': typeof SiteLearnPathSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/': typeof SiteIndexRoute
  '/_site/articles/$slug': typeof SiteArticlesSlugRoute
  '/_site/roadmaps/$slug': typeof SiteRoadmapsSlugRoute
  '/_site/articles/': typeof SiteArticlesIndexRoute
  '/_site/learn/': typeof SiteLearnIndexRoute
  '/_site/roadmaps/': typeof SiteRoadmapsIndexRoute
  '/_site/learn/$pathSlug/$lessonSlug': typeof SiteLearnPathSlugLessonSlugRoute
  '/_site/learn/$pathSlug/': typeof SiteLearnPathSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles/$slug'
    | '/roadmaps/$slug'
    | '/articles/'
    | '/learn/'
    | '/roadmaps/'
    | '/learn/$pathSlug/$lessonSlug'
    | '/learn/$pathSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles/$slug'
    | '/roadmaps/$slug'
    | '/articles'
    | '/learn'
    | '/roadmaps'
    | '/learn/$pathSlug/$lessonSlug'
    | '/learn/$pathSlug'
  id:
    | '__root__'
    | '/_site'
    | '/_site/'
    | '/_site/articles/$slug'
    | '/_site/roadmaps/$slug'
    | '/_site/articles/'
    | '/_site/learn/'
    | '/_site/roadmaps/'
    | '/_site/learn/$pathSlug/$lessonSlug'
    | '/_site/learn/$pathSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/articles/': {
      id: '/_site/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof SiteArticlesIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/articles/$slug': {
      id: '/_site/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof SiteArticlesSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/learn/': {
      id: '/_site/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof SiteLearnIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/roadmaps/': {
      id: '/_site/roadmaps/'
      path: '/roadmaps'
      fullPath: '/roadmaps/'
      preLoaderRoute: typeof SiteRoadmapsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/roadmaps/$slug': {
      id: '/_site/roadmaps/$slug'
      path: '/roadmaps/$slug'
      fullPath: '/roadmaps/$slug'
      preLoaderRoute: typeof SiteRoadmapsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/learn/$pathSlug/': {
      id: '/_site/learn/$pathSlug/'
      path: '/learn/$pathSlug'
      fullPath: '/learn/$pathSlug/'
      preLoaderRoute: typeof SiteLearnPathSlugIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/learn/$pathSlug/$lessonSlug': {
      id: '/_site/learn/$pathSlug/$lessonSlug'
      path: '/learn/$pathSlug/$lessonSlug'
      fullPath: '/learn/$pathSlug/$lessonSlug'
      preLoaderRoute: typeof SiteLearnPathSlugLessonSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteIndexRoute: typeof SiteIndexRoute
  SiteArticlesSlugRoute: typeof SiteArticlesSlugRoute
  SiteRoadmapsSlugRoute: typeof SiteRoadmapsSlugRoute
  SiteArticlesIndexRoute: typeof SiteArticlesIndexRoute
  SiteLearnIndexRoute: typeof SiteLearnIndexRoute
  SiteRoadmapsIndexRoute: typeof SiteRoadmapsIndexRoute
  SiteLearnPathSlugLessonSlugRoute: typeof SiteLearnPathSlugLessonSlugRoute
  SiteLearnPathSlugIndexRoute: typeof SiteLearnPathSlugIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteIndexRoute: SiteIndexRoute,
  SiteArticlesSlugRoute: SiteArticlesSlugRoute,
  SiteRoadmapsSlugRoute: SiteRoadmapsSlugRoute,
  SiteArticlesIndexRoute: SiteArticlesIndexRoute,
  SiteLearnIndexRoute: SiteLearnIndexRoute,
  SiteRoadmapsIndexRoute: SiteRoadmapsIndexRoute,
  SiteLearnPathSlugLessonSlugRoute: SiteLearnPathSlugLessonSlugRoute,
  SiteLearnPathSlugIndexRoute: SiteLearnPathSlugIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
